[tools]
golangci-lint = '2.6'

[tasks.b]
run = "go build -o ./dof ./cmd/dof/main.go"

[tasks.lint]
run = "golangci-lint run"

[tasks.test]
run = "go test github.com/mithcs/dof/internal/..."

[tasks.build]
depends = ["lint", "test"]
run = "go build -ldflags='-s -w' -o ./dof ./cmd/dof/main.go"
